# Generated by Django 4.2.7 on 2023-11-12 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('responsable', 'Responsable'), ('pompiste', 'Pompiste')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=255)),
                ('Password1', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
