# Generated by Django 4.2.7 on 2023-11-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Password1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
