# Generated by Django 4.2.6 on 2023-11-04 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pompe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('nv_index', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anc_index', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ventes_images/')),
                ('id_pompe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pompe.pompe')),
                ('id_pompiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
