# Generated by Django 4.2.6 on 2023-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuve',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
