# Generated by Django 4.2.6 on 2023-11-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuve', '0002_alter_cuve_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuve',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
