# Generated by Django 4.2.6 on 2023-12-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_remove_station_id_users'),
        ('cuve', '0003_cuve_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuve',
            name='Nb_pmp_alimente',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='Qt_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='id_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.station'),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='stocke',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
