# Generated by Django 4.2.6 on 2023-10-31 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('Nmbr_cuves', models.IntegerField()),
                ('Nmbr_pompes', models.IntegerField()),
                ('Nmbr_pompistes', models.IntegerField()),
                # ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
