# Generated by Django 4.2.6 on 2023-11-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_station_id_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
