# Generated by Django 4.2.7 on 2023-11-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_password_remove_profile_password1_and_more'),
        ('station', '0003_station_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='responsables',
            field=models.ManyToManyField(related_name='stations', to='users.profile'),
        ),
    ]
