# Generated by Django 4.2.6 on 2023-11-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuve', '0001_initial'),
        ('pompiste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('id_cuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuve.cuve')),
                ('id_pompiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pompiste.pompiste')),
            ],
        ),
    ]
