# Generated by Django 4.2.7 on 2023-11-16 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pompiste', '0003_pompiste_cuve_pompiste_pompe_pompiste_station_and_more'),
        ('pompe', '0003_alter_pompe_id_pompiste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompe',
            name='id_pompiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pompes', to='pompiste.pompiste'),
        ),
    ]
